# Generated by Django 3.2.4 on 2023-12-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesa', models.IntegerField()),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobrable', models.BooleanField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(blank=True, default=1)),
                ('tipo', models.CharField(blank=True, choices=[('c', 'Comida'), ('b', 'Bebida')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idOrden', models.IntegerField()),
                ('idMenu', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('nota', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cocina', models.IntegerField(default=0)),
                ('bebida', models.IntegerField(default=0)),
                ('agregado', models.BooleanField(default=0)),
                ('nuevo', models.BooleanField(default=1)),
                ('comanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trajineras.comanda')),
            ],
        ),
    ]
