# Generated by Django 3.2.4 on 2023-12-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, choices=[('c', 'Comida'), ('b', 'Bebida')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idOrden', models.IntegerField()),
                ('idMenu', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesa', models.IntegerField()),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('cocina', models.BooleanField(blank=True, default=0)),
                ('bebida', models.BooleanField(blank=True, default=0)),
                ('cobrable', models.BooleanField(blank=True, default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.CharField(max_length=150)),
            ],
        ),
    ]
