# Generated by Django 3.2.4 on 2023-12-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajineras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmenu',
            name='nuevo',
            field=models.BooleanField(default=0),
        ),
    ]
